name: 'build and deploy on gke'
author: 'p0x0q-dev'
description: |-
  GCPのWorkload Identityを使って、Docker Build, GKE Deploymentを行うComposite 


inputs:
  WORKLOAD_IDENTITY_PROVIDER:
    description: "The workload identity provider to use"
    required: true

  SERVICE_ACCOUNT:
    description: "The service account to use"
    required: true

  GAR_LOCATION:
    description: "The location of the Google Artifact Registry"
    required: true

  PROJECT_ID:
    description: "The project ID"
    required: true

  REPOSITORY:
    description: "The repository name"
    required: true

  IMAGE:
    description: "The image name"
    required: true

  GKE_CLUSTER:
    description: "The GKE cluster name"
    required: true

  GKE_ZONE:
    description: "The GKE cluster zone"
    required: true

  DEPLOYMENT_NAME:
    description: "The deployment name"
    required: true

  OIDC_AUDIENCE:
    description: "The OIDC audience"
    required: true

  DEPLOY_ENV:
    description: "The deployment environment"
    required: true

  NAMESPACE:
    description: "The namespace"
    required: true

runs:
  using: "composite"
  steps:
    # runs-on: ubuntu-latest
    # timeout-minutes: 30
    # permissions:
    #   contents: "read"
    #   id-token: "write"

    - uses: actions/checkout@v3
    - id: "auth"
      name: "Authenticate to Google Cloud"
      uses: "google-github-actions/auth@v1"
      with:
        token_format: "access_token"
        workload_identity_provider: ${{ inputs.WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ inputs.SERVICE_ACCOUNT }}
        audience: ${{ inputs.OIDC_AUDIENCE }}

    - name: Docker configuration
      run: |-
        echo ${{steps.auth.outputs.access_token}} | docker login -u oauth2accesstoken --password-stdin https://${{ inputs.GAR_LOCATION }}-docker.pkg.dev
      shell: bash

    - name: Set up GKE credentials
      uses: google-github-actions/get-gke-credentials@v1
      with:
        cluster_name: ${{ inputs.GKE_CLUSTER }}
        location: ${{ inputs.GKE_ZONE }}


    - name: App Build
      working-directory: ./
      run: |-
        docker build \
          --tag "${{ inputs.GAR_LOCATION }}-docker.pkg.dev/${{ inputs.PROJECT_ID }}/${{ inputs.REPOSITORY }}/${{ inputs.IMAGE }}:$GITHUB_SHA" \
          --build-arg GITHUB_SHA="$GITHUB_SHA" \
          --build-arg GITHUB_REF="$GITHUB_REF" \
          -f ./Dockerfile .
      shell: bash

    - name: App Publish
      working-directory: ./
      run: |-
        docker push "${{ inputs.GAR_LOCATION }}-docker.pkg.dev/${{ inputs.PROJECT_ID }}/${{ inputs.REPOSITORY }}/${{ inputs.IMAGE }}:$GITHUB_SHA"
      shell: bash

    # - uses: actions/checkout@v3
    # - id: "auth"
    #   name: "Authenticate to Google Cloud"
    #   uses: "google-github-actions/auth@v1"
    #   with:
    #     token_format: "access_token"
    #     workload_identity_provider: ${{ inputs.WORKLOAD_IDENTITY_PROVIDER }}
    #     service_account: ${{ inputs.SERVICE_ACCOUNT }}
    #     audience: ${{ inputs.OIDC_AUDIENCE }}

    - name: Set up Kustomize
      working-directory: k8s/overlayes/${{ inputs.DEPLOY_ENV }}
      run: |-
        curl -sfL https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv5.0.3/kustomize_v5.0.3_linux_amd64.tar.gz | tar xz
        chmod u+x ./kustomize
        mv ./kustomize /usr/local/bin
      shell: bash

    - name: App Deploy
      working-directory: k8s/overlayes/${{ inputs.DEPLOY_ENV }}
      run: |-
        /usr/local/bin/kustomize edit set image image=${{ inputs.GAR_LOCATION }}-docker.pkg.dev/${{ inputs.PROJECT_ID }}/${{ inputs.REPOSITORY }}/${{ inputs.IMAGE }}:$GITHUB_SHA
        /usr/local/bin/kustomize build . | kubectl apply -f -
        kubectl rollout status deployment/${{ inputs.DEPLOYMENT_NAME}} -n ${{ inputs.NAMESPACE }} --timeout=20m
        # 初回デプロイ時には、kubectl rollout status が失敗することがあるので1秒ほど待機させる
        sleep 1
        kubectl get services -o wide -n ${{ inputs.NAMESPACE }} || true

        kubectl get pods -n ${{ inputs.NAMESPACE }} | grep OutOfcpu | awk '{print $1}' | xargs kubectl delete pods -n ${{ inputs.NAMESPACE }} || true
      shell: bash

branding:
  icon: 'cloud'
  color: 'blue'
